#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

# Detect host LAN IP from the active interface (Wi-Fi en0, then Ethernet en1)
HOST_IP=""
for iface in en0 en1 en2 en3; do
  ip=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
  if [ -n "$ip" ]; then
    HOST_IP="$ip"
    ACTIVE_IFACE="$iface"
    break
  fi
done

if [ -z "$HOST_IP" ]; then
  echo "ERROR: Could not detect host LAN IP on en0-en3" >&2
  exit 1
fi

export ZM_SSL_IP="$HOST_IP"

CERT_FILE="$(pwd)/zm/config/ssl/cert.cer"

echo "=============================================="
echo " Host IP detected: $HOST_IP (interface: $ACTIVE_IFACE)"
echo " SSL cert will be pinned to: $HOST_IP"
echo ""
echo " Connect from your browser at:"
echo "   http://$HOST_IP"
echo "   https://$HOST_IP"
echo "=============================================="

# Remember the current cert so we can tell if the container regenerates it.
OLD_FP=""
[ -f "$CERT_FILE" ] && OLD_FP=$(openssl x509 -in "$CERT_FILE" -noout -fingerprint -sha256 2>/dev/null || true)

# Always start detached.
docker compose up -d "$@"

# The cert is (re)generated by the container's init script during startup.
# Wait for it to reflect the host IP so we can detect a regeneration.
printf "Waiting for SSL cert"
for _ in $(seq 1 60); do
  if [ -f "$CERT_FILE" ] && openssl x509 -in "$CERT_FILE" -noout -ext subjectAltName 2>/dev/null | grep -qF "IP Address:$HOST_IP"; then
    break
  fi
  printf "."
  sleep 1
done
echo ""

NEW_FP=""
[ -f "$CERT_FILE" ] && NEW_FP=$(openssl x509 -in "$CERT_FILE" -noout -fingerprint -sha256 2>/dev/null || true)

CERT_MATCHES=0
if [ -f "$CERT_FILE" ] && openssl x509 -in "$CERT_FILE" -noout -ext subjectAltName 2>/dev/null | grep -qF "IP Address:$HOST_IP"; then
  CERT_MATCHES=1
fi

if [ "$CERT_MATCHES" -ne 1 ]; then
  echo "WARNING: SSL cert is not valid for $HOST_IP yet."
  echo "  Check: docker compose logs zoneminder | grep -i ssl"
elif [ "$NEW_FP" != "$OLD_FP" ]; then
  echo "=============================================="
  echo " SSL cert was (re)generated for $HOST_IP."
  echo " Install it in the macOS keychain so your"
  echo " browser trusts https://$HOST_IP"
  echo "=============================================="
  if [ -t 0 ]; then
    read -r -p "Install cert into the System keychain now? (needs admin password) [y/N] " ans || ans=""
    if [[ "$ans" =~ ^[Yy]$ ]]; then
      if sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$CERT_FILE"; then
        echo "Cert installed and trusted. Restart your browser to pick it up."
      else
        echo "Install failed — retry manually with the command below."
      fi
    fi
  fi
  echo "To (re)install later, run:"
  echo "  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain \"$CERT_FILE\""
else
  echo "SSL cert already valid for $HOST_IP (unchanged)."
fi

echo ""
echo "Stack is up (detached). Follow logs with:  docker compose logs -f"
